name       : libpinyin
version    : 2.2.0
release    : 6
source     :
    - https://github.com/libpinyin/libpinyin/archive/2.2.0.tar.gz : 334bc20cae54ed8ab158a9ab7845f3b4148615d71a278f258fd1d5834b2b75cf
    - https://superb-sea2.dl.sourceforge.net/project/libpinyin/models/model15.text.tar.gz : 9e77a4fc8fa3d00adbca8df3c33f7c37f34e14a9c84ad7743af99e5444b768f5
license    : GPL-2.0
component  : programming
summary    : Library to deal with pinyin.
description: |
    The libpinyin project aims to provide the algorithms core for intelligent sentence-based Chinese pinyin input methods.
builddeps  :
    - autoconf-archive
    - db5-devel
setup      : |
    tar xvf $sources/model15.text.tar.gz -C data/
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
