name       : libpinyin
version    : 1.6.0
release    : 1
source     :
    - https://github.com/libpinyin/libpinyin/archive/1.6.0.tar.gz : ca4a33f01fb4301cfad1f977276823f0172b1aa5736046a5c2ca73c474386e37
license    : GPL-2.0
component  : programming
summary    : Library to deal with pinyin.
description: |
    The libpinyin project aims to provide the algorithms core for intelligent sentence-based Chinese pinyin input methods.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
