name       : libpinyin
version    : 2.6.1
release    : 8
source     :
    - https://github.com/libpinyin/libpinyin/archive/refs/tags/2.6.1.tar.gz : 936c756bf57205f064eb7731772289b2e9769ba5b52d6be957a17a9d3b4d5d0f
    - https://sourceforge.net/projects/libpinyin/files/models/model19.text.tar.gz/download : 56422a4ee5966c2c809dd065692590ee8def934e52edbbe249b8488daaa1f50b
license    : GPL-3.0-only
component  : programming.library
summary    : Library to deal with pinyin.
description: |
    The libpinyin project aims to provide the algorithms core for intelligent sentence-based Chinese pinyin input methods.
replaces   :
    - libzhuyin # libzhuyin was merged into libpinyin
builddeps  :
    - autoconf-archive
    - db5-devel
setup      : |
    tar xvf $sources/download -C data/
    %reconfigure --disable-static --with-dbm=BerkeleyDB --enable-libzhuyin
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
