name       : libpinyin
version    : 2.0.0
release    : 5
source     :
    - https://github.com/libpinyin/libpinyin/archive/2.0.0.tar.gz : 0b78b483c179f6998a0df582aea3d77340bb1e9d887b52ed8fae677d535fd19d
    - https://superb-sea2.dl.sourceforge.net/project/libpinyin/models/model14.text.tar.gz : 185f0f175a90bcfc55cf3cf6ceff8d447a6269492c0ca1a1fc0748ea2c181363
license    : GPL-2.0
component  : programming
summary    : Library to deal with pinyin.
description: |
    The libpinyin project aims to provide the algorithms core for intelligent sentence-based Chinese pinyin input methods.
builddeps  :
    - autoconf-archive
setup      : |
    tar xvf $sources/model14.text.tar.gz -C data/
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
