name       : libpinyin
version    : 2.3.0
release    : 7
source     :
    - https://github.com/libpinyin/libpinyin/archive/2.3.0.tar.gz : 00cb09f267031fb528bebc4621268037fca64677040123ebb184a50afcb43430
    - https://sourceforge.net/projects/libpinyin/files/models/model17.text.tar.gz/download : e017278ab022bca065a744ccbbede94db8932ec3fb64592a1693627db9b662cd
license    : GPL-2.0-or-later
component  : programming
summary    : Library to deal with pinyin.
description: |
    The libpinyin project aims to provide the algorithms core for intelligent sentence-based Chinese pinyin input methods.
builddeps  :
    - autoconf-archive
    - db5-devel
setup      : |
    tar xvf $sources/download -C data/
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
