name       : libpinyin
version    : 1.9.91
release    : 4
source     :
    - https://github.com/libpinyin/libpinyin/archive/1.9.91.tar.gz : 619ed7858df152b24d9fb9eb37edb1a0e43acd7482cef61478068799aa4af012
    - https://superb-sea2.dl.sourceforge.net/project/libpinyin/models/model14.text.tar.gz : 185f0f175a90bcfc55cf3cf6ceff8d447a6269492c0ca1a1fc0748ea2c181363
license    : GPL-2.0
component  : programming
summary    : Library to deal with pinyin.
description: |
    The libpinyin project aims to provide the algorithms core for intelligent sentence-based Chinese pinyin input methods.
builddeps  :
    - autoconf-archive
setup      : |
    # Lets download this file the right way
    sed -i '/wget http/d' data/Makefile.am
    ln -s $sources/model14.text.tar.gz data/model14.text.tar.gz

    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
